[package]
name = "cgol"
version = "0.1.0"
authors = ["Joshua Read, joshua-read@hotmail.co.uk"]
edition = "2018"
default-run = "visualiser"

[dependencies]
rand = "0.7.2"
libm = "0.2.1"
clap = "2.33.0"
